export const batchesData = [
    { id: 1, name: "FSD-March Morning", course: "Full Stack Web Development", student: "Alice Johnson", instructor: "David Miller", initials: "DM", status: "Active", trainingDays: "Monday - Friday", duration: "3 months", startDate: "Jan 15, 2024", timing: "09:00AM - 12:00 PM", studentCount: 25 },
    { id: 2, name: "UI/UX-April Evening", course: "User Interface Design", student: "Bob Wilson", instructor: "Sarah Smith", initials: "SS", status: "Completed", trainingDays: "Monday - Thursday", duration: "2 months", startDate: "Feb 10, 2024", timing: "06:00PM - 08:00 PM", studentCount: 18 },
    { id: 3, name: "Python-May Weekend", course: "Python Programming", student: "Charlie Brown", instructor: "Michael Ross", initials: "MR", status: "Active", trainingDays: "Saturday - Sunday", duration: "4 months", startDate: "Mar 05, 2024", timing: "10:00AM - 02:00 PM", studentCount: 30 },
    { id: 4, name: "Data Science-June", course: "Advanced Data Science", student: "Diana Prince", instructor: "Jessica Pearson", initials: "JP", status: "Active", trainingDays: "Mon, Wed, Fri", duration: "6 months", startDate: "Apr 12, 2024", timing: "09:00AM - 11:30 AM", studentCount: 22 },
    { id: 5, name: "React Native-July", course: "Mobile Development", student: "Ethan Hunt", instructor: "Harvey Specter", initials: "HS", status: "Completed", trainingDays: "Monday - Friday", duration: "3 months", startDate: "May 20, 2024", timing: "02:00PM - 05:00 PM", studentCount: 15 },
    { id: 6, name: "Node.js-August", course: "Backend Engineering", student: "Fiona Apple", instructor: "Louis Litt", initials: "LL", status: "Active", trainingDays: "Tuesday, Thursday", duration: "3 months", startDate: "Jun 08, 2024", timing: "07:00PM - 09:30 PM", studentCount: 28 },
    { id: 7, name: "DevOps-September", course: "Cloud & Devops", student: "George Miller", instructor: "Donna Paulsen", initials: "DP", status: "Active", trainingDays: "Monday - Friday", duration: "4 months", startDate: "Jul 15, 2024", timing: "10:30AM - 01:30 PM", studentCount: 20 },
    { id: 8, name: "Java Fullstack-Oct", course: "Java Development", student: "Hannah Montana", instructor: "Mike Ross", initials: "MR", status: "Inactive", trainingDays: "Monday - Saturday", duration: "5 months", startDate: "Aug 22, 2024", timing: "08:00AM - 10:30 AM", studentCount: 35 },
    { id: 9, name: "Angular-November", course: "Frontend with Angular", student: "Ian Wright", instructor: "Rachel Zane", initials: "RZ", status: "Inactive", trainingDays: "Mon, Wed, Fri", duration: "3 months", startDate: "Sep 10, 2024", timing: "04:00PM - 06:30 PM", studentCount: 24 },
    { id: 10, name: "Cyber Security-Dec", course: "Ethical Hacking", student: "Jack Sparrow", instructor: "David Miller", initials: "DM", status: "Active", trainingDays: "Weekend Only", duration: "6 months", startDate: "Oct 05, 2024", timing: "09:00AM - 04:00 PM", studentCount: 12 },
    { id: 11, name: "Mobile App Dev-Jan", course: "Swift & Flutter", student: "Kelly Kapowski", instructor: "Sarah Smith", initials: "SS", status: "Active", trainingDays: "Monday - Friday", duration: "3 months", startDate: "Nov 12, 2024", timing: "09:00AM - 12:00 PM", studentCount: 19 },
    { id: 12, name: "Cloud Computing-Feb", course: "AWS & Azure", student: "Liam Neeson", instructor: "Michael Ross", initials: "MR", status: "Completed", trainingDays: "Mon, Wed, Fri", duration: "4 months", startDate: "Dec 15, 2024", timing: "06:00PM - 08:30 PM", studentCount: 26 },
];
